routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();
Route::post('/print','Cashier\BillController@print')->name('print');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['role:Super-Admin']], function () {
        Route::resource('settings', Admin\SettingController::class);
        Route::resource('permissions', Admin\PermissionController::class);
        Route::resource('roles', Admin\RoleController::class);
    });
    // Route::group(['middleware' => ['role:Super-Admin|Admin|Tester']], function () {

    // });


    Route::group(['middleware' => ['role:Super-Admin|Admin|Tester|User']], function () {
        Route::resource('users', Admin\UserController::class);
        Route::resource('foods', Admin\FoodController::class);
        Route::resource('stocks', Admin\StockController::class);
        Route::resource('category', Admin\CategoryController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::resource('schemes', Admin\SchemeController::class);
        Route::get('report', 'Admin\ReportController@index')->name('report.index');
        Route::get('report/stocks', 'Admin\ReportController@stocks')->name('report.stocks');
        Route::get('report/orders', 'Admin\ReportController@orders')->name('report.orders');
        Route::get('report/users', 'Admin\ReportController@users')->name('report.users');
    });
    Route::group(['middleware' => ['role:Super-Admin|Admin|Cashier|Tester|User']], function () {
        Route::get('report/current-user', 'Admin\ReportController@currentUserCollection')->name('report.currentUserCollection');
        Route::get('report/current-user/history', 'Admin\ReportController@historyCurrentUserCollection')->name('report.historyCurrentUser');
        Route::resource('dashboard', Admin\DashboardController::class);

        Route::resource('generalstocks', Cashier\StockController::class);
        Route::get('billing', 'Cashier\BillController@index')->name('billing.index');
        Route::post('billing/checkout', 'Cashier\BillController@checkout')->name('billing.checkout');


        Route::get('order/cancel/{order_id}', 'Admin\ReportController@cancelOrder')->name('order.cancel');
        Route::get('user/profile', 'Admin\UserController@profile')->name('user.profile');
    });
});

    // Route::get('billing/index', 'Cashier\BillController@index')->name('billing.index');

    // Route::post('billing\search', 'Cashier\BillController@search')->name('billing.search');

    // Route::get('/add-to-cart/{food}','Cashier\CartController@add')->name('cart.add');
    // Route::get('/cart','Cashier\CartController@index')->name('cart.index');
    // Route::get('/cart/destroy/{itemId}','Cashier\CartController@destroy')->name('cart.destroy');
    // Route::get('/cart/update/{rowId}','Cashier\CartController@update')->name('cart.update');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = [
        'app_name', 'restaurant_address', 'restaurant_name', 'contact_number', 'restaurant_logo'
    ];
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Setting;
use Session;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $setting = Setting::find(1)->first();
        return view('pages.setting.index')->with('setting', $setting);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $request->validate([
            'restaurant_name' => 'required|string',
            'restaurant_address' => 'required|string',
            'contact_number' => 'required'
        ]);
        $data = $request->only(['restaurant_name', 'restaurant_address', 'contact_number', 'app_name']);
        // //Check if new img
        if ($request->hasFile('image')) {
            //upload it
            $image = $request->image->store('setting');
            //delete
            $data['restaurant_logo'] = $image;
        } else {
            $image = 'category/default-category.png';
        }


        $setting->update($data);
        // dd($setting);
        if($request->app_name){
            Session::put('app_name',$request->app_name);
        }
        Session::put('settings_restaurant_name', $request->restaurant_name);
        Session::put('settings_restaurant_address', $request->restaurant_address);
        Session::put('settings_contact_number', $request->contact_number);
        Session::put('settings_restaurant_logo', $image);

        toastr()->success('Settings Updated Successfully.', 'Successfully!!!');


        return redirect(route('settings.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/setting/edit.blade.php
@extends('layouts.app')
@section('content')


<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row mt-0 mt-lg-8">

                <div class="col-xl-12">
                    <!--begin::Advance Table Widget 1-->
                    <div class="card card-custom card-stretch card-shadowless gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 py-5">
                            <h3 class="card-title align-items-start flex-column">
                                <span class="card-label font-weight-bolder text-dark">Settings</span>
                                <span class="text-muted mt-3 font-weight-bold font-size-sm">Update Settings</span>
                            </h3>

                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body py-0">
                            <form action="{{ route('settings.update',1)}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="name">Restaurant name</label>
                                    <input type="text" class="form-control" id="" name="name" value="{{ $setting ? $setting->name ? ''  }}">
                                    @error('name')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="price">Price</label>
                                    <input type="number" class="form-control" id="price" name='price' value="{{ $food->price }}">
                                    @error('price')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                {{-- <div class="form-group">
																			<label for="image">image</label>
																			<input type="{{ isset($food) ? 'hidden' : 'file'}}" class="form-control" id="image" name="image">
                        </div> --}}


                        <div class="form-group">
                            <label for="category">Category</label>
                            <select name="category" id="category" class="form-control">
                                <option value="">
                                    @foreach($categories as $category)
                                <option value="{{ $category->id }}" @if(isset($food)) @if($category->id ===
                                    $food->category_id)
                                    selected
                                    @endif
                                    @endif
                                    >
                                    {{$category->name}}
                                </option>
                                @endforeach
                                </option>
                            </select>
                            @error('category_id')
                            <div class="alert-danger">{{ $message }}</div>
                            @enderror
                        </div>



                        <div class="form-group">
                            <button class="btn btn-success" type="submit">
                                Update Food Item
                            </button>
                        </div>
                        </form>
                    </div>

                </div>
                <!--end::Body-->
            </div>
            <!--end::Advance Table Widget 1-->
        </div>
    </div>
    <!--end::Row-->
    <!--begin::Row-->

    <!--end::Row-->



    <!--end::Dashboard-->
    <!--end::Container-->
</div>
</div>
@endsection

resources/views/pages/setting/index.blade.php
@extends('layouts.app')
@section('content')


<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row mt-0 mt-lg-8">

                <div class="col-xl-12">
                    <!--begin::Advance Table Widget 1-->
                    <div class="card card-custom card-stretch card-shadowless gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 py-5">
                            <h3 class="card-title align-items-start flex-column">
                                <span class="card-label font-weight-bolder text-dark">Settings</span>
                                <span class="text-muted mt-3 font-weight-bold font-size-sm">Update Settings</span>
                            </h3>

                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body py-0">
                            <form action="{{ route('settings.update',1)}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="app_name">App name : </label>
                                    @role('Super-Admin')
                                    <input type="text" class="form-control" id="" name="app_name"
                                        value="{{ $setting->app_name  }}">
                                    @endrole
                                    @role('Admin|Cashier|Tester')
                                    <h4>{{ $setting->app_name  }}</h4>
                                    @endrole
                                    @error('app_name')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="restaurant_name">Restaurant name</label>
                                    <input type="text" class="form-control" id="" name="restaurant_name"
                                        value="{{ $setting->restaurant_name  }}">
                                    @error('restaurant_name')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="restaurant_address">Restaurant Address</label>
                                    <input type="text" class="form-control" id="" name="restaurant_address"
                                        value="{{ $setting->restaurant_address  }}">
                                    @error('restaurant_address')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="contact_number">Contact Number</label>
                                    <input type="text" class="form-control" id="" name="contact_number"
                                        value="{{ $setting->contact_number  }}">
                                    @error('contact_number')
                                    <div class="alert-danger">{{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="image">Logo</label>
                                    <input type="file" class="form-control" id="image" name="image">
                                </div>
                                @if(isset($setting))
                                <div class="form-group">
                                    <img src="{{ asset('storage/'.$setting->restaurant_logo) }}" alt=""
                                        style="width:60px;height:60px;">
                                </div>
                                @endif



                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">
                                        Update Setting
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!--end::Body-->
                </div>
                <!--end::Advance Table Widget 1-->
            </div>
        </div>
        <!--end::Row-->
        <!--begin::Row-->

        <!--end::Row-->



        <!--end::Dashboard-->
        <!--end::Container-->
    </div>
</div>
@endsection