routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();
Route::post('/print','Cashier\BillController@print')->name('print');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['role:Super-Admin']], function () {
        Route::resource('settings', Admin\SettingController::class);
        Route::resource('permissions', Admin\PermissionController::class);
        Route::resource('roles', Admin\RoleController::class);
    });
    // Route::group(['middleware' => ['role:Super-Admin|Admin|Tester']], function () {

    // });


    Route::group(['middleware' => ['role:Super-Admin|Admin|Tester|User']], function () {
        Route::resource('users', Admin\UserController::class);
        Route::resource('foods', Admin\FoodController::class);
        Route::resource('stocks', Admin\StockController::class);
        Route::resource('category', Admin\CategoryController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::resource('schemes', Admin\SchemeController::class);
        Route::get('report', 'Admin\ReportController@index')->name('report.index');
        Route::get('report/stocks', 'Admin\ReportController@stocks')->name('report.stocks');
        Route::get('report/orders', 'Admin\ReportController@orders')->name('report.orders');
        Route::get('report/users', 'Admin\ReportController@users')->name('report.users');
    });
    Route::group(['middleware' => ['role:Super-Admin|Admin|Cashier|Tester|User']], function () {
        Route::get('report/current-user', 'Admin\ReportController@currentUserCollection')->name('report.currentUserCollection');
        Route::get('report/current-user/history', 'Admin\ReportController@historyCurrentUserCollection')->name('report.historyCurrentUser');
        Route::resource('dashboard', Admin\DashboardController::class);

        Route::resource('generalstocks', Cashier\StockController::class);
        Route::get('billing', 'Cashier\BillController@index')->name('billing.index');
        Route::post('billing/checkout', 'Cashier\BillController@checkout')->name('billing.checkout');


        Route::get('order/cancel/{order_id}', 'Admin\ReportController@cancelOrder')->name('order.cancel');
        Route::get('user/profile', 'Admin\UserController@profile')->name('user.profile');
    });
});

    // Route::get('billing/index', 'Cashier\BillController@index')->name('billing.index');

    // Route::post('billing\search', 'Cashier\BillController@search')->name('billing.search');

    // Route::get('/add-to-cart/{food}','Cashier\CartController@add')->name('cart.add');
    // Route::get('/cart','Cashier\CartController@index')->name('cart.index');
    // Route::get('/cart/destroy/{itemId}','Cashier\CartController@destroy')->name('cart.destroy');
    // Route::get('/cart/update/{rowId}','Cashier\CartController@update')->name('cart.update');

app/Scheme.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Scheme extends Model
{
    protected $fillable = [
        'food_id', 'quantity', 'status', 'start_date', 'end_date'
    ];
    public function food()
    {
        return $this->belongsTo(Food::class);
    }
}

app/Http/Controllers/Admin/SchemeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Food;
use App\Http\Controllers\Controller;
use App\Scheme;
use App\Setting;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;

class SchemeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.scheme.index')->with('schemes', Scheme::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.scheme.create')->with('foods', Food::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'food' => 'required',
            'quantity' => 'required',
            'start_date' => 'required',
        ]);
        $scheme = Scheme::where('food_id', $request->food)->first();
        if ($scheme) {
            toastr()->error('Scheme Already exists for ' . $scheme->food->name, 'Sorry!!!');

            return redirect()->back();
        }
        if ($request->has('end_date')) {
            $end_date = $request->end_date;
        } else {
            $end_date = $request->start_date;
        }

        Scheme::create([
            'food_id' => $request->food,
            'quantity' => $request->quantity,
            'start_date' => $request->start_date,
            'end_date' => $end_date,
        ]);
        toastr()->success('Scheme Created Successfully.', 'Successfully!!!');

        return redirect(route('schemes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Scheme $scheme)
    {
        return view('pages.scheme.edit', compact('scheme'))->with('foods', Food::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Scheme $scheme)
    {
        $request->validate([
            'food' => 'required',
            'quantity' => 'required',
            'start_date' => 'required',
        ]);
        if ($request->has('end_date')) {
            $end_date = $request->end_date;
        } else {
            $end_date = $request->start_date;
        }
        $scheme->quantity = $request->input(
            'quantity'
        );
        $scheme->start_date = $request->input(
            'start_date'
        );
        $scheme->end_date = $end_date;
        $scheme->save();
        toastr()->success('Scheme Updated Successfully.', 'Successfully!!!');

        return redirect(route('schemes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Scheme $scheme)
    {
        $scheme->delete();

        toastr()->success('Scheme Deleted Successfully.', 'Successfully!!!');


        return redirect(route('schemes.index'));
    }
}

resources/views/pages/scheme/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row mt-0 mt-lg-8">

                <div class="col-xl-12">
                    <!--begin::Advance Table Widget 1-->
                    <div class="card card-custom card-stretch card-shadowless gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 py-5">
                            <h3 class="card-title align-items-start flex-column">
                                <span class="card-label font-weight-bolder text-dark">Scheme Management</span>
                                <span class="text-muted mt-3 font-weight-bold font-size-sm">Create schemes</span>
                            </h3>

                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body py-0">
                            <form action="{{ route('schemes.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group">
                                    <label for="food">Food Name</label>
                                    <select name="food" id="food" class="form-control" required>
                                        <option value="">
                                            @foreach($foods as $food)
                                        <option value="{{ $food->id }}">
                                            {{$food->name}}
                                        </option>
                                        @endforeach
                                        </option>
                                    </select>
                                    @error('name')
                                    <div class="alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="quantity">Quantity</label>
                                    <div class="input-group">

                                        <input type="number" class="form-control" name='quantity' min="0"
                                            required /><br>
                                        @error('quantity')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="start_date">Start Date</label>
                                    <div class="input-group">

                                        <input type="date" class="form-control" name='start_date' required /><br>
                                        @error('start_date')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="end_date">End Date</label>
                                    <div class="input-group">

                                        <input type="date" class="form-control" name='end_date' /><br>
                                        @error('end_date')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">
                                        Create Scheme
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!--end::Body-->
                </div>
                <!--end::Advance Table Widget 1-->
            </div>
        </div>
        <!--end::Row-->
        <!--begin::Row-->

        <!--end::Row-->



        <!--end::Dashboard-->
        <!--end::Container-->
    </div>
</div>
@endsection

resources/views/pages/scheme/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row mt-0 mt-lg-8">

                <div class="col-xl-12">
                    <!--begin::Advance Table Widget 1-->
                    <div class="card card-custom card-stretch card-shadowless gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 py-5">
                            <h3 class="card-title align-items-start flex-column">
                                <span class="card-label font-weight-bolder text-dark">Scheme Management</span>
                                <span class="text-muted mt-3 font-weight-bold font-size-sm">Edit scheme</span>
                            </h3>

                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body py-0">
                            <form action="{{ route('schemes.update',$scheme->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @method('put')
                                @csrf

                                <div class="form-group">
                                    <label for="food">Food Name</label>
                                    <input type="text" class="form-control" value="{{$scheme->food->name}}" disabled>
                                    <input type="hidden" value="{{ $scheme->food->id }}" name="food">

                                    @error('food')
                                    <div class="alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="quantity">Quantity</label>
                                    <div class="input-group">

                                        <input type="number" class="form-control" name='quantity' min="0"
                                            value="{{$scheme->quantity}}" required /><br>
                                        @error('quantity')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="start_date">Start Date</label>
                                    <div class="input-group">

                                        <input type="date" class="form-control" name='start_date'
                                            value="{{$scheme->start_date}}" required /><br>
                                        @error('start_date')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="end_date">End Date</label>
                                    <div class="input-group">

                                        <input type="date" class="form-control" name='end_date'
                                            value="{{$scheme->end_date}}" /><br>
                                        @error('end_date')
                                        <div class="alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">
                                        Update Scheme
                                    </button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!--end::Body-->
                </div>
                <!--end::Advance Table Widget 1-->
            </div>
        </div>
        <!--end::Row-->
        <!--begin::Row-->

        <!--end::Row-->



        <!--end::Dashboard-->
        <!--end::Container-->
    </div>
</div>
@endsection

resources/views/pages/scheme/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row mt-0 mt-lg-8">

                <div class="col-xl-12">
                    <!--begin::Advance Table Widget 1-->
                    <div class="card card-custom card-stretch card-shadowless gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 py-5">
                            <h3 class="card-title align-items-start flex-column">
                                <span class="card-label font-weight-bolder text-dark">Scheme Management</span>
                                <span class="text-muted mt-3 font-weight-bold font-size-sm">Manage your schemes</span>
                            </h3>
                            <div class="card-toolbar">
                                <a href="{{route('schemes.create')}}"
                                    class="btn btn-success font-weight-bolder font-size-sm mx-3">
                                    <span class="svg-icon svg-icon-md svg-icon-white  ">
                                        <!--begin::Svg Icon | path:assets/media/svg/icons/Communication/Add-user.svg-->
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                            xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
                                            viewBox="0 0 24 24" version="1.1">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24" />
                                                <rect fill="#000000" opacity="0.3" x="12" y="4" width="3" height="13"
                                                    rx="1.5" />
                                                <rect fill="#000000" opacity="0.3" x="7" y="9" width="3" height="8"
                                                    rx="1.5" />
                                                <path
                                                    d="M5,19 L20,19 C20.5522847,19 21,19.4477153 21,20 C21,20.5522847 20.5522847,21 20,21 L4,21 C3.44771525,21 3,20.5522847 3,20 L3,4 C3,3.44771525 3.44771525,3 4,3 C4.55228475,3 5,3.44771525 5,4 L5,19 Z"
                                                    fill="#000000" fill-rule="nonzero" />
                                                <rect fill="#000000" opacity="0.3" x="17" y="11" width="3" height="6"
                                                    rx="1.5" />
                                            </g>
                                        </svg>
                                        <!--end::Svg Icon-->
                                    </span>Add Scheme</a>

                            </div>
                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body py-0">
                            <!--begin::Table-->
                            <div class="table-responsive">
                                <table class="table table-head-custom table-vertical-center"
                                    id="kt_advance_table_widget_1">
                                    <thead>
                                        <tr class="text-left">
                                            <th class="pl-0" style="width: 20px">

                                            </th>
                                            <th class="pr-0" style="width: 100px">Food Name</th>
                                            <th style="min-width: 200px"></th>
                                            <th style="min-width: 150px">Scheme Quantity</th>
                                            <th style="min-width: 150px">Start Date</th>
                                            <th style="min-width: 150px">End Date</th>
                                            <th class="pr-0 text-right" style="min-width: 150px">action</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @if($schemes->count()>0)
                                        @foreach($schemes as $scheme)
                                        <tr>
                                            <th class="pl-0" style="width: 20px">

                                            </th>
                                            <td class="pr-0">
                                                <div class="symbol symbol-50 symbol-light mt-1">
                                                    <span class="symbol-label">
                                                        <img src="{{ asset('storage/'. $scheme->food->food_image) }}"
                                                            class="h-75 align-self-end" alt="" />
                                                    </span>
                                                </div>
                                            </td>
                                            <td class="pl-0">
                                                <a href="#"
                                                    class="text-dark-75 font-weight-bolder text-hover-primary mb-1 font-size-lg">{{$scheme->food->name}}</a>
                                            </td>
                                            <td>
                                                <span
                                                    class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ $scheme->quantity }}</span>
                                            </td>
                                            <td>
                                                <span
                                                    class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ $scheme->start_date }}</span>
                                            </td>
                                            <td>
                                                <span
                                                    class="text-dark-75 font-weight-bolder d-block font-size-lg">{{ $scheme->end_date }}</span>
                                            </td>

                                            <td class="pr-0 text-right">
                                                <a href="{{ route('schemes.edit',$scheme->id) }}"
                                                    class="btn btn-icon btn-light btn-hover-primary btn-sm">
                                                    <span class="svg-icon svg-icon-md svg-icon-primary">
                                                        <!--begin::Svg Icon | path:assets/media/svg/icons/Communication/Write.svg-->
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                            xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                            height="24px" viewBox="0 0 24 24" version="1.1">
                                                            <g stroke="none" stroke-width="1" fill="none"
                                                                fill-rule="evenodd">
                                                                <rect x="0" y="0" width="24" height="24" />
                                                                <path
                                                                    d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                                    fill="#000000" fill-rule="nonzero"
                                                                    transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)" />
                                                                <path
                                                                    d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                                    fill="#000000" fill-rule="nonzero" opacity="0.3" />
                                                            </g>
                                                        </svg>
                                                        <!--end::Svg Icon-->
                                                    </span>
                                                </a>

                                                <a href="{{ route('schemes.destroy',$scheme->id) }}"
                                                    class="btn btn-icon btn-light btn-hover-primary btn-sm">
                                                    <span class="svg-icon svg-icon-md svg-icon-primary">
                                                        <!--begin::Svg Icon | path:assets/media/svg/icons/General/Trash.svg-->
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                            xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                            height="24px" viewBox="0 0 24 24" version="1.1">
                                                            <g stroke="none" stroke-width="1" fill="none"
                                                                fill-rule="evenodd">
                                                                <rect x="0" y="0" width="24" height="24" />
                                                                <path
                                                                    d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                                                                    fill="#000000" fill-rule="nonzero" />
                                                                <path
                                                                    d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                                    fill="#000000" opacity="0.3" />
                                                            </g>
                                                        </svg>
                                                        <!--end::Svg Icon-->
                                                    </span>
                                                </a>
                                            </td>
                                        </tr>



                            </div>


                            @endforeach
                            @else
                            <tr>
                                <th class="pl-0" style="width: 20px">

                                </th>

                                <td rowspan="6">No schemes to show</td>
                            </tr>
                            @endif

                            </tbody>
                            </table>
                        </div>
                        <!--end::Table-->
                    </div>
                    <!--end::Body-->
                </div>
                <!--end::Advance Table Widget 1-->
            </div>
        </div>
        <!--end::Row-->
        <!--begin::Row-->

        <!--end::Row-->



        <!--end::Dashboard-->
    </div>
    <!--end::Container-->
</div>

</div>

@endsection