routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();
Route::post('/print','Cashier\BillController@print')->name('print');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['role:Super-Admin']], function () {
        Route::resource('settings', Admin\SettingController::class);
        Route::resource('permissions', Admin\PermissionController::class);
        Route::resource('roles', Admin\RoleController::class);
    });
    // Route::group(['middleware' => ['role:Super-Admin|Admin|Tester']], function () {

    // });


    Route::group(['middleware' => ['role:Super-Admin|Admin|Tester|User']], function () {
        Route::resource('users', Admin\UserController::class);
        Route::resource('foods', Admin\FoodController::class);
        Route::resource('stocks', Admin\StockController::class);
        Route::resource('category', Admin\CategoryController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::resource('schemes', Admin\SchemeController::class);
        Route::get('report', 'Admin\ReportController@index')->name('report.index');
        Route::get('report/stocks', 'Admin\ReportController@stocks')->name('report.stocks');
        Route::get('report/orders', 'Admin\ReportController@orders')->name('report.orders');
        Route::get('report/users', 'Admin\ReportController@users')->name('report.users');
    });
    Route::group(['middleware' => ['role:Super-Admin|Admin|Cashier|Tester|User']], function () {
        Route::get('report/current-user', 'Admin\ReportController@currentUserCollection')->name('report.currentUserCollection');
        Route::get('report/current-user/history', 'Admin\ReportController@historyCurrentUserCollection')->name('report.historyCurrentUser');
        Route::resource('dashboard', Admin\DashboardController::class);

        Route::resource('generalstocks', Cashier\StockController::class);
        Route::get('billing', 'Cashier\BillController@index')->name('billing.index');
        Route::post('billing/checkout', 'Cashier\BillController@checkout')->name('billing.checkout');


        Route::get('order/cancel/{order_id}', 'Admin\ReportController@cancelOrder')->name('order.cancel');
        Route::get('user/profile', 'Admin\UserController@profile')->name('user.profile');
    });
});

    // Route::get('billing/index', 'Cashier\BillController@index')->name('billing.index');

    // Route::post('billing\search', 'Cashier\BillController@search')->name('billing.search');

    // Route::get('/add-to-cart/{food}','Cashier\CartController@add')->name('cart.add');
    // Route::get('/cart','Cashier\CartController@index')->name('cart.index');
    // Route::get('/cart/destroy/{itemId}','Cashier\CartController@destroy')->name('cart.destroy');
    // Route::get('/cart/update/{rowId}','Cashier\CartController@update')->name('cart.update');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name','category_image'];
    public function foods()
    {
        return $this->hasMany(Food::class);
    }
    public function stock(){
        return $this->belongsTo(Stock::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // https://doc-04-6o-docs.googleusercontent.com/docs/securesc/0lnpimq0e0ngr4444uvgk7o7mq2ps5c0/ibc63ttj7d3aj72grepe3oo7ot8j7oq5/1607322900000/12507546150029939768/02810936856288739991/1sj5OsmQu3GnTOzovgNbYGEKgAWTNZYZX?e=download&authuser=0&nonce=j014lscs3o9am&user=02810936856288739991&hash=79g3kt6fr8mev3ue8p8a0ni81qgremfl

    public function index()
    {
        return view('pages.category.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
        ]);
        if ($request->hasFile('image')) {
            $image = $request->image->store('category');
        } else {
            $image = 'category/default-category.png';
        }
        // dd($image);

        Category::create([
            'name' => $request->name,
            'category_image' => $image
        ]);


        toastr()->success('Category Added Successfully.', 'Successfully!!!');

        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('pages.category.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required|string'
        ]);
        $data = $request->only(['name']);
        //Check if new img
        if ($request->hasFile('image')) {
            //upload it
            $image = $request->image->store('category');
            //delete
            $category->deleteImage();
            $data['category_image'] = $image;
        } else {
            $image = 'category/default-category.png';
            $data['category_image'] = $image;
        }


        $category->update($data);

        toastr()->success('Category Updated Successfully.', 'Finally!!!');


        return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if ($category->foods->count() > 0) {
            session()->flash('error', 'category cannot be deleted');
            return redirect()->back();
        }
        $category->delete();
        session()->flash('success', 'category deleted successfully');


        return redirect(route('categories.index'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default ">
    <div class="card-header">
        {{ isset($category) ? 'Edit Category' : 'Create Category'}}
    </div>
    <div class="card-body">

        <form action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }}"
            method="POST">
            @csrf
            @if( isset($category))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" class="form-control" name="name"
                    value="{{ isset($category) ? $category->name : '' }}">
                    {{-- {{ $errors->first('name') }} --}}
                                        @error('name')
            <div class="alert-danger">{{ $message }}</div>
            @enderror
            
            </div>
            <div class="form-group">
                <button class="btn btn-success">
                    {{ isset($category) ? 'Update Category' : 'Add Category' }}

                </button>
            </div>

        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-end mb-2">
    <a href="{{ route('category.create') }}" class="btn btn-success ">Add Category</a>

</div>
<div class="card card-default ">
    <div class="card-header">
        Categories
    </div>
    <div class="card-body">

        <table class="table">
            <thead>
                <th>Name</th>
                <th>Food Count</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($categories as $category)
                <tr>
                    <td>
                        {{ $category->name }}
                    </td>
                    <td>
                        {{$category->foods->count()}}
                    </td>
                    <td>
                        <a href="{{ route('category.edit',$category->id) }}" class="btn btn-info btn-small">
                            Edit
                        </a>
                        <form action="{{ route('category.destroy',$category->id) }}" method="POST">

                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>

                @endforeach
            </tbody>
        </table>
    </div>
</div>


</div>
</div>
@endsection

